CREATE DATABASE BOOKLEASE;

USE BOOKLEASE;

CREATE TABLE USERS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATION_DATE DATETIME,
    STATUS VARCHAR(45)
);

CREATE TABLE CATEGORY(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL
);

CREATE TABLE BOOKS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(45) NOT NULL,
    AUTHOR VARCHAR(45) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    IMAGE_PATH VARCHAR(255) NOT NULL,
    FK_CATEGORY INT,
    ACTIVE BOOLEAN,
    FOREIGN KEY (FK_CATEGORY) REFERENCES CATEGORY (ID)
);

CREATE TABLE USER_ACCESS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_USER INT,
    FK_BOOK INT,
    RELEASE_DATE DATETIME,
    EXPIRATION_DATE DATETIME,
    FOREIGN KEY (FK_USER) REFERENCES USERS (ID),
    FOREIGN KEY (FK_BOOK) REFERENCES BOOKS (ID)
);

CREATE TABLE PLAN(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_ACESS BOOLEAN
);

CREATE TABLE SUBSCRIPTION(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_USER INT,
    FK_PLAN INT,
    START_DATE DATETIME,
    END_DATE DATETIME,
    STATUS VARCHAR(45),
    FOREIGN KEY (FK_USER) REFERENCES USERS (ID),
    FOREIGN KEY (FK_PLAN) REFERENCES PLAN (ID)
);
